### ISSUE TITLE
https://www.learnpython.org/pl/

### ISSUE THREAD

**Issue by lolipopes** [ronreiter/interactive-tutorials#454]
Traceback (most recent call last):
  File "/usr/lib/python3.5/py_compile.py", line 125, in compile
    _optimize=optimize)
  File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./prog.py", line 5
    print "Hello, World!"
                        ^
SyntaxError: Missing parentheses in call to 'print'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/py_compile.py", line 129, in compile
    raise py_exc
py_compile.PyCompileError:   File "./prog.py", line 5
    print "Hello, World!"
                        ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by lolipopes** [comment]
> Traceback (most recent call last):
> File "/usr/lib/python3.5/py_compile.py", line 125, in compile
> _optimize=optimize)
> File "", line 735, in source_to_code
> File "", line 222, in _call_with_frames_removed
> File "./prog.py", line 5
> print "Hello, World!"
> ^
> SyntaxError: Missing parentheses in call to 'print'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "", line 1, in
> File "/usr/lib/python3.5/py_compile.py", line 129, in compile
> raise py_exc
> py_compile.PyCompileError: File "./prog.py", line 5
> print "Hello, World!"
> ^
> SyntaxError: Missing parentheses in call to 'print'
